### PR TITLE
Enabled shared HttpClient and WebSocket; Fixed minor SAT findings;

### PR DESCRIPTION
**Pull request by cweitkamp**
- Enabled shared `HttpClient` and `WebSocket`
- Fixed minor SAT findings;

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by octa22** [comment]
Hi, thank you very much for the PR, unfortunately the shared HttpClient and WebSocket do not work - the thing initialization results in exception because they are stopped.
Tested on OH 2.4 and 2.5.0M1
```
2019-07-02 22:34:51.289 [DEBUG] [vektiva.handler.VektivaSmarwiHandler] - Exception during status update
java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: HttpClient@650bd76{STOPPED} is stopped
        at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
        at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101) ~[?:?]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:684) ~[?:?]
        at org.openhab.binding.vektiva.handler.VektivaSmarwiHandler.checkStatus(VektivaSmarwiHandler.java:173) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.util.concurrent.RejectedExecutionException: HttpClient@650bd76{STOPPED} is stopped
        at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:282) ~[?:?]
        at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:247) ~[?:?]
        at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:578) ~[?:?]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:727) ~[?:?]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:680) ~[?:?]
```

**Comment by octa22** [comment]
But it seems that it works in latest 2.5.0-SNAPSHOT...
is this possible?

**Comment by cweitkamp** [comment]
Did you run an old version of the binding before? Did you try to restart OH after installing the new binding version? I have the slight feeling that both instances got stopped because of your current code.

**Comment by octa22** [comment]
you are right, the restart did the trick, thank you!

**Pull request merged**
